// Tech stack data structured in categories
export const techStackData = {
	frontend: [
		{
			name: "Angular",
			initials: "A",
			color: "bg-red-600",
			textColor: "text-white",
		},
		{
			name: "React",
			initials: "⚛️",
			color: "bg-blue-400",
			textColor: "text-white",
		},
		{
			name: "React Native",
			initials: "RN",
			color: "bg-blue-500",
			textColor: "text-white",
		},
		{
			name: "Next.js",
			initials: "N",
			color: "bg-black",
			textColor: "text-white",
		},
		{
			name: "HTML",
			initials: "H",
			color: "bg-orange-500",
			textColor: "text-white",
		},
		{
			name: "CSS",
			initials: "C",
			color: "bg-blue-300",
			textColor: "text-white",
		},
		{
			name: "Tailwind CSS",
			initials: "T",
			color: "bg-cyan-500",
			textColor: "text-white",
		},
		{
			name: "PrimeReact",
			initials: "P",
			color: "bg-blue-600",
			textColor: "text-white",
		},
		{
			name: "Motion",
			initials: "M",
			color: "bg-purple-600",
			textColor: "text-white",
		},
		{
			name: "Webflow",
			initials: "W",
			color: "bg-blue-400",
			textColor: "text-white",
		},
		{
			name: "Electron",
			initials: "E",
			color: "bg-gray-700",
			textColor: "text-white",
		},
		{
			name: "Storybook",
			initials: "S",
			color: "bg-pink-500",
			textColor: "text-white",
		},
	],
	backend: [
		{
			name: ".NET",
			initials: "N",
			color: "bg-purple-700",
			textColor: "text-white",
		},
		{
			name: "C#",
			initials: "C#",
			color: "bg-purple-600",
			textColor: "text-white",
		},
		{
			name: "Node.js",
			initials: "N",
			color: "bg-green-600",
			textColor: "text-white",
		},
		{
			name: "WordPress",
			initials: "W",
			color: "bg-blue-500",
			textColor: "text-white",
		},
	],
	database: [
		{
			name: "SQL",
			initials: "S",
			color: "bg-blue-600",
			textColor: "text-white",
		},
		{
			name: "Firebase",
			initials: "F",
			color: "bg-orange-500",
			textColor: "text-white",
		},
	],
	tools: [
		{
			name: "Git",
			initials: "G",
			color: "bg-red-500",
			textColor: "text-white",
		},
		{
			name: "GitHub",
			initials: "GH",
			color: "bg-gray-800",
			textColor: "text-white",
		},
		{
			name: "GitLab",
			initials: "GL",
			color: "bg-orange-500",
			textColor: "text-white",
		},
		{
			name: "Docker",
			initials: "D",
			color: "bg-blue-600",
			textColor: "text-white",
		},
		{
			name: "Azure DevOps",
			initials: "AD",
			color: "bg-blue-500",
			textColor: "text-white",
		},
		{
			name: "Azure Entra",
			initials: "AE",
			color: "bg-blue-600",
			textColor: "text-white",
		},
		{
			name: "Atlassian",
			initials: "A",
			color: "bg-blue-500",
			textColor: "text-white",
		},
		{
			name: "TeamCity",
			initials: "TC",
			color: "bg-blue-400",
			textColor: "text-white",
		},
		{
			name: "OctoDeploy",
			initials: "OD",
			color: "bg-purple-500",
			textColor: "text-white",
		},
		{
			name: "Sentry",
			initials: "S",
			color: "bg-red-600",
			textColor: "text-white",
		},
	],
	testing: [
		{
			name: "Vitest",
			initials: "V",
			color: "bg-green-500",
			textColor: "text-white",
		},
		{
			name: "Cypress",
			initials: "C",
			color: "bg-gray-700",
			textColor: "text-white",
		},
		{
			name: "Playwright",
			initials: "P",
			color: "bg-blue-600",
			textColor: "text-white",
		},
	],
	development: [
		{
			name: "JavaScript",
			initials: "JS",
			color: "bg-yellow-500",
			textColor: "text-black",
		},
		{
			name: "TypeScript",
			initials: "TS",
			color: "bg-blue-500",
			textColor: "text-white",
		},
		{
			name: "Vite",
			initials: "V",
			color: "bg-purple-500",
			textColor: "text-white",
		},
		{
			name: "BiomeJS",
			initials: "B",
			color: "bg-green-600",
			textColor: "text-white",
		},
		{
			name: "ESLint",
			initials: "E",
			color: "bg-purple-600",
			textColor: "text-white",
		},
		{
			name: "Prettier",
			initials: "P",
			color: "bg-pink-500",
			textColor: "text-white",
		},
		{
			name: "NgRx",
			initials: "N",
			color: "bg-red-600",
			textColor: "text-white",
		},
		{
			name: "MCP",
			initials: "M",
			color: "bg-blue-700",
			textColor: "text-white",
		},
	],
};
