// Tech stack data structured in categories
export const techStackData = {
	frontend: [
		{ name: "Angular", iconUrl: "/icons/angular.svg" },
		{ name: "React", iconUrl: "/icons/react.svg" },
		{ name: "React Native", iconUrl: "/icons/react.svg" },
		{ name: "Next.js", iconUrl: "/icons/nextjs.svg" },
		{ name: "ViteJs", iconUrl: "/icons/vitejs.svg" },
		{ name: "HTML", iconUrl: "/icons/html.svg" },
		{ name: "CSS", iconUrl: "/icons/css.svg" },
		{ name: "Tailwind CSS", iconUrl: "/icons/tailwindcss.svg" },
		{ name: "PrimeReact", iconUrl: "/icons/primereact.svg" },
		{ name: "Motion", iconUrl: "/icons/motion.svg" },
		{ name: "Webflow", iconUrl: "/icons/webflow.svg" },
		{ name: "Electron", iconUrl: "/icons/electron.svg" },
		{ name: "Storybook", iconUrl: "/icons/storybook.svg" },
		{ name: "React Query", iconUrl: "/icons/reactquery.svg" },
		{ name: "Zustand", iconUrl: "/icons/zustand.svg" },
		{ name: "Redux", iconUrl: "/icons/redux.svg" },
		{ name: "RxJS", iconUrl: "/icons/rxjs.svg" },
	],
	backend: [
		{ name: ".NET", iconUrl: "/icons/dotnet.svg" },
		{ name: "C#", iconUrl: "/icons/csharp.svg" },
		{ name: "Node.js", iconUrl: "/icons/nodejs.svg" },
		{ name: "WordPress", iconUrl: "/icons/wordpress.svg" },
		{ name: "PayloadCMS", iconUrl: "/icons/payloadcms.svg" },
	],
	database: [
		{ name: "SQL", iconUrl: "/icons/sql.svg" },
		{ name: "Firebase", iconUrl: "/icons/firebase.svg" },
	],
	tools: [
		{ name: "Git", iconUrl: "/icons/git.svg" },
		{ name: "GitHub", iconUrl: "/icons/github.svg" },
		{ name: "GitLab", iconUrl: "/icons/gitlab.svg" },
		{ name: "Docker", iconUrl: "/icons/docker.svg" },
		{ name: "Azure DevOps", iconUrl: "/icons/azure.svg" },
		{ name: "Azure Entra", iconUrl: "/icons/azure.svg" },
		{ name: "Atlassian", iconUrl: "/icons/atlassian.svg" },
		{ name: "TeamCity", iconUrl: "/icons/teamcity.svg" },
		{ name: "Sentry", iconUrl: "/icons/sentry.svg" },
		{ name: "Asana", iconUrl: "/icons/asana.svg" },
		{ name: "Google Analytics", iconUrl: "/icons/googleanalytics.svg" },
		{ name: "PostHog", iconUrl: "/icons/posthog.svg" },
	],
	testing: [
		{ name: "Vitest", iconUrl: "/icons/vitest.svg" },
		{ name: "Cypress", iconUrl: "/icons/cypress.svg" },
		{ name: "Playwright", iconUrl: "/icons/playwright.svg" },
	],
	development: [
		{ name: "TypeScript", iconUrl: "/icons/typescript.svg" },
		{ name: "JavaScript", iconUrl: "/icons/javascript.svg" },
		{ name: "Figma", iconUrl: "/icons/figma.svg" },
		{ name: "VS Code", iconUrl: "/icons/vscode.svg" },
		{ name: "Cursor", iconUrl: "/icons/cursor.svg" },
	],
};
